//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracTakipApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Device
    {
        public int DeviceId { get; set; }

        [DisplayName("Plaka Numarasý")]
        [Required(ErrorMessage = "Plaka Numarasý zorunludur.")]
        public string LicenseNo { get; set; }

        public int UnitID { get; set; }
        public int BrandID { get; set; }

        [DisplayName("Model")]
        [Required(ErrorMessage = "Model alaný zorunludur.")]
        public string Model { get; set; }

        [DisplayName("Tür")]
        [Required(ErrorMessage = "Tür alaný zorunludur.")]
        public bool Kind { get; set; }

        [DisplayName("Çeþit")]
        [Required(ErrorMessage = "Çeþit alaný zorunludur.")]
        public bool Type { get; set; }

        [DisplayName("Araç Durumu")]
        [Required(ErrorMessage = "Araç Durumu alaný zorunludur.")]
        public bool DeviceSituation { get; set; }

        [DisplayName("Model Yýlý")]
        [Required(ErrorMessage = "Model Yýlý alaný zorunludur.")]
        public short ModelYear { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
