//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracTakipApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class UserAccount
    {
        public int UserID { get; set; }

        [DisplayName("Ad")]
        [Required(ErrorMessage = "Ad alaný zorunludur.")]
        public string FirstName { get; set; }

        [DisplayName("Soyad")]
        [Required(ErrorMessage = "Soyad alaný zorunludur.")]
        public string LastName { get; set; }

        [DisplayName("Kullanýcý Adý")]
        public string UserName { get; set; }

        [DisplayName("Parola")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Parola girilmesi zorunludur.")]
        public string Password { get; set; }

        [DisplayName("Parola Doðrulamam")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Lütfen parolanýzý doðrulayýnýz.")]
        public string ConfirmPassword { get; set; }
    }
}
